[theme]
primaryColor="#4991f5"
backgroundColor="#f5f5f5"
secondaryBackgroundColor="#7ca0fb"
textColor="#0a0a0a"
font="serif"

def set_bg_hack_url():
    ''' 
    A function to unpack an image from url and set as bg. 
    Returns 
    ------- 
    The background. 
    ''' 
          
    st.markdown( 
          f""" 
          <style> 
         .stApp {{ 
              background: url("https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linkedin.com%2Fpulse%2Fusing-artificial-intelligence-help-mental-health-shelley-goodman-mba-kpudc&psig=AOvVaw1mQVphZiA_S7XdkzNLhYj2&ust=1719350349209000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCID6sq6V9YYDFQAAAAAdAAAAABAp"); 
              background-size: cover 
          }} 
          </style> 
          """, 
          unsafe_allow_html=True 
      ) 

set_bg_hack_url()